server:
  port: 9001
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql:///security_authorty?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: 123456
  main:
    allow-bean-definition-overriding: true
mybatis:
  type-aliases-package: com.itcast.domain
  configuration:
    map-underscore-to-camel-case: true
logging:
  level:
    com.itcast: debug